



def main(argv):
    import subprocess, os, re
    import csv
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument('file', type=argparse.FileType('r'), nargs='+')
    #parser.add_argument('file')
    args = parser.parse_args()
    for f in args.file:
        print f.name
        file = f.name

        filename=file.split("/")[-1]
        typelessFilename= filename.replace("."+filename.split(".")[-1],"")

        data=[]

        with open(file, "r") as input:
            line_data={}

            for line in input: #read line by line the the output file generated by the benchmark tool
                #print line
                if re.search("\AComputing", line):
                    if line_data is not None:
                        data.append(line_data)
                        line_data={}
                    type_s=line.split("time")[0].replace("Computing","").strip()
                    rep=re.findall(r'\b\d+\b',line)
                    #print "BENCH",type,rep[-1]
                    line_data["BENCH"]=type_s
                    line_data["reps"]=rep[-1]
                if re.search("\AComputing TASK DEPENDENCY", line):
                    line_data["deps"]=line.replace("Computing TASK DEPENDENCY","").split(" ")[2].strip()

                if "BENCH" in  line_data.keys():
                    if re.search("\A"+line_data["BENCH"]+"\s*\w*\s*[0-9]*\s*time", line):
                        line_data["time"] = line.split("=")[1].split(" ")[1].strip()
                        line_data["time_A"] = line.split("=")[1].split(" ")[-1].strip()
                    if re.search("\A"+line_data["BENCH"]+"\s*\w*\s*[0-9]*\s*overhead", line):
                        line_data["overhead"] = line.split("=")[1].split(" ")[1].strip()
                        line_data["overhead_A"] = line.split("=")[1].split(" ")[-1].strip()


                if re.search("\A\w*\s+[0-9]*.[0-9]*\s+[0-9]*.[0-9]*\s+[0-9]*.[0-9]*\s+[0-9]*.[0-9]*\s+[0-9]*.[0-9]*\s+[0-9]*.[0-9]*", line):
                    #print line
                    tmp = line.split()
                    prefix = tmp[0]
                    line_data[prefix+"_Sample_size"] = tmp[1]
                    line_data[prefix+"_Average"] = tmp[2]
                    line_data[prefix+"_Min"] = tmp[3]
                    line_data[prefix+"_Max"] = tmp[4]
                    line_data[prefix+"_S.D."] = tmp[5]
                    line_data[prefix+"_CONF95"] = tmp[6]
                    line_data[prefix+"_OVERHEAD"] = tmp[7]
                    line_data[prefix+"_OVERHEAD_CONF95"] = tmp[8]
                    line_data[prefix+"_Outliers"] = tmp[9]

        data.append(line_data)


        #for line in data:
        #    print line
        keys = data[-1].keys()
        with open(typelessFilename+'.csv', 'wb') as output_file:
            dict_writer = csv.DictWriter(output_file, keys)
            dict_writer.writeheader()
            dict_writer.writerows(data)#

if __name__ == "__main__":
    import sys
    main(sys.argv)
