# Uncomment the following line to use OpenMP 2.0 features
#OMPFLAG = -DOMPVER2
# Uncomment the following line to use OpenMP 3.0 features
OMPFLAG = -DOMPVER2 -DOMPVER3

CC=gcc 
CXX=g++ -std=c++11
CFLAGS =  -O1 -lm -fopenmp -ggdb
LDFLAGS = -O0 -lm -fopenmp
CPP = /usr/bin/cpp
LIBS = 
